In [119]:
import pandas as pd
import numpy as np

In [120]:
up1 = pd.read_csv("ulsan_place_1.csv", encoding="utf-8")
up2 = pd.read_csv("ulsan_place_2.csv", encoding="utf-8")

up = pd.concat([up1, up2], ignore_index=True)
up

       Unnamed: 0       url                                            content
0               0   이마트/울산점  추석때 회사에서 받은 신세계 상품권이 있어서 사용할겸~ 장도 볼겸 구경을 하러 갔어...
1               1   이마트/울산점  ​​​몇일 전 신랑의 전화 나 #얀센 예약했다 #얀센​어떻게???​​​​민방위 선착...
2               2   이마트/울산점  ​저희가족은 가끔 장을 볼 때 이마트를 자주가요!특히 아이들 데리고 가기도 넘 좋고...
3               3   이마트/울산점  ​안녕하세요 오늘도 먹는다 오먹입니다​어제 오늘 날씨가 너무 우중충하네요 어제는 비...
4               4   이마트/울산점  안녕하세요. 신창입니다.추석연휴가 끝난후 바쁜 일주일이 었습니다.이마트 울산점 토이...
...           ...       ...                                                ...
85399       41383  동천야외물놀이장  오늘은 7/16 토요일주말은 어딜가든 사람이 많지만어제 따끈따끈하게 개장한 울산 동...
85400       41384  동천야외물놀이장  코로나로 인해 2019년 여름 이후 휴장했던울산 야외물놀이장을 3년 만에 개장했다는...
85401       41385  동천야외물놀이장  2022년 여름 울산 동천 야외 물놀이장이 개장했어요! 울산에서 가장 인기 많은 야...
85402       41386  동천야외물놀이장  ​​​2022 울산 동천 물놀이장 개장정보 울산 야외 수영장 중 단 두곳 뿐인 유로...
85403       41387  동천야외물놀이장  안녕하세요. ​울산광역시 중구청 울산큰애기 SNS 서포터즈 박기언입니다.​오늘 소개...

[85404 rows x 3 columns]

In [121]:
up["url"].unique()

array(['이마트/울산점', '현대백화점/울산점', '롯데백화점/울산점', '롯데마트/울산점', '홈플러스/울산남구점',
       '업스퀘어', '울산농수산물도매시장', '장생포고래박물관', '울산대공원', '장생포고래문화마을', '세이브존/울산점',
       '선암호수공원', '울산도서관', '뉴코아아울렛/울산점', '신정시장', '다이소/울산삼산본점',
       '삼성전자서비스/남울산센터', '롯데영플라자/울산점', '문수월드컵경기장', '수암상가시장', 'CGV/울산삼산',
       '공업탑', '장보고식자재마트/옥동점', '태화강동굴피아', '문수실내수영장', '울산산업공구월드',
       '롯데시네마/울산', '교보문고/울산점', '야음시장', '울산대공원장미축제', '삼성전자서비스/서울산휴대폰센터',
       '무지개놀이터', '울산과학관', '고래생태체험관', '울산번개시장', '다이소/울산신정점', '하나로마트/옥동점',
       '노브랜드/울산달동점', '장생포문화창고', '아토즈캠핑/울산점', '롯데하이마트/메가스토어울산점', '울산박물관',
       '가자주류백화점/울산점', '울산대공원/동물원', '울산남부도서관', '프리모리캠핑/울산점', '장생포모노레일',
       '울산항만선착장', '정광사', '울산남구국민체육센터', '수암회수산시장', '궁거랑벚꽃길', '와우쥬',
       '상개골프연습장', '문수야구장', '파크애비뉴', '문수국제양궁장', '도산도서관', '울산골프클럽',
       '삼성디지털프라자/남울산점', '더프트앤도프트/울산더테라스가든점', '리치웰휘트니스/울산점', '다이소/울산무거점',
       '문수테니스장', '문수체육관', '레져마트', '정토사', '삼성디지털프라자/서울산본점', '태화강국가정원/삼호지구',
       '태화강전망대', 'LG전자서비스센터/남울산점', '다이소/울산타임스퀘어점', '중앙농협하나로마트', '울산골프학교',
       '다이소/울산옥동점', '골프존파크/삼산한국골프점', '가족문화센터', '울산신항용연부두', '세상타일도기',
       '달동삼성아파트상가', 'KBS울산홀', '대왕암공원', '대왕암공원출렁다리', '일산해수욕장', '주전몽돌해변',
       '슬도', '홈플러스/울산동구점', '현대백화점/울산동구점', '울산대교전망대', '방어진항', '방어진활어센터',
       '슬도등대', '테라스파크', '울기등대', '일산수산물판매센터', '쇠평어린이공원', '대송농수산물시장',
       '방어진공동어시장', '다이소/울산일산지점', '동울산종합시장', '삼성전자서비스/동울산센터', '현대예술관',
       '대왕별아이누리', '남목마성시장', '전하체육센터', '월봉시장', '울산테마식물수목원', 'CGV/대왕암',
       '울산동부도서관', '울산수협방어진위판장', '울산항/염포부두', '소리체험관', '주전항', '다이소/울산방어점',
       '서부시민운동장', '노브랜드/울산방어점', '화암추등대', '울산현대프로축구단/클럽하우스', '방어진구방파제',
       '동구국민체육센터', '한마음회관', 'LG전자서비스센터/동울산점', '한마음마트/방어점',
       '방어진방파제회센터밀양상회', '주전십리벚꽃누리길', '롯데하이마트/동구일산점', '다이소/울산남목점', '다이소',
       '요트탈래', '대왕암일산랜드', '꽃바위문화관', '상진방파제', '한마음회관/수영장', '디디바바문구라인',
       '전하시장', '행복낚시', '농부총각', '울산대왕암관광안내소', '세계로마트/전하점', 'GS25/울산솔밭해변점',
       '올리브영/울산테라스파크점', '화암방파제', '명덕호수공원', '홈플러스익스프레스/울산방어점', '꽃나루공원',
       '한마음마트/꽃바위점', '털보낚시', '남목도서관', '세계로마트', '월봉사', '협성문구센터',
       '슬도유채꽃군락지', '하나로마트/방어진농협방어점', '울산동구야구장', '코스트코홀세일/울산점', '롯데마트/진장점',
       '메가마트/울산점', '홈플러스/울산북구점', '모다아울렛/울산점', '신선도원몰', '울산농협농수산물종합유통센터',
       '울산공항', '정자항', '정자해수욕장', '고릴라캠핑/울산점', '하나로마트/울산점', 'CGV/울산진장',
       '탑마트/울산화봉점', '송정박상진호수공원', '삼성전자서비스/북울산센터', '강동몽돌해변', '캠핑고래/울산점',
       '하나로마트/신천지점', 'CGV/울산신천', '디디바바문구센터', '홈씨씨/울산점', '편백산림욕장',
       '연암철물공구종합상사', '호계시장', '노브랜드/울산신천점', '다이소/울산신천점', '농소종합운동장',
       '몬스터식자재할인마트', '네오골프연습장', '화봉종합시장', '다이소/화봉점', '울산진장디플렉스',
       '울산시중앙도서관', '트래블러/울산점', '다이소/진장점', '리홈쿠첸서비스센터/울산점', '매곡도서관',
       '롯데하이마트/효문점', '블루마씨네자동차극장', 'LG전자베스트샵/북울산본점', '쇠부리체육센터',
       '다이소/울산호계점', '오치골공원', '호계문화체육센터', '효문운동장', '박상진의사생가', '구암문구/북구점',
       '태화강억새군락지', '당사방파제', '다이소/울산강동산하점', '토이앤맘/울산점', '삼성디지털프라자/북울산본점',
       '유니클로/울산진장점', '신명해변', '베이스타즈CC/건축중(2022년03월개장예정)', '울산안전체험관',
       'LG전자서비스센터/북울산점', '농소1동도서관', '당사해양낚시공원', '달천철장유적공원', '정자활어직매장',
       '강동화암주상절리', '베이스타즈CC', '신명방파제', '다이소/울산상안동점', '판지항', '준토이아울렛',
       '북구국민체육센터', 'K스포츠타운', '하나로마트/농소농협', '마인드휘트니스/울산점', '달천운동장',
       '울산낚시백화점', '하나로마트/무룡지점', '제전항', '모던욕실', '세현공구철물전기안전총판', '화동못수변공원',
       '양정생활체육공원', '온리스포츠배드민턴센터', '모던하우스/울산진장상설점', '간절곶', '진하해수욕장',
       '언양자수정동굴나라', '언양알프스시장', '메가마트/언양점', '간절곶소망우체통', '하나로마트/울산원예농협',
       '가천린포크', '석남사', '남창옹기종기시장', '덕하시장(오일장)', '나사리해수욕장', '탑마트/언양점',
       '작천정계곡', '탑마트/울산천상점', '울산간절곶해맞이축제', '탑마트/울산구영점', '반구대암각화', '덕신소공원',
       '자드락숲', '다이소/울산언양점', '울산전시컨벤션센터', '언양자연체험장', '영남알프스복합웰컴센터', '언양읍성',
       '선바위', '울산암각화박물관', '하나로마트/범서농협점', '캠핑트렁크/울산점', '태화강생태관',
       '신불산폭포자연휴양림', '나사리방파제', '울주선바위도서관', '탑마트/울산남창점', '울산발리온천', '간월재',
       '다원푸드우리마트언양점', '더골프클럽', '울주작천정벚꽃길', '울주천전리각석', '영남알프스번개맨체험관',
       '울산대곡박물관', 'GS더프레시/울산구영점', '등억온천지구', '하나로마트/서생농협진하점', '울주군국민체육센터',
       '서생포왜성', '금아드림스퀘어', '신암1리방파제', '가지산탄산유황천', '솔개해수욕장', '울산옹기박물관',
       '울산CC', '자수정동굴나라썰매장', '온산문화체육센터', '다이소/울산덕신점', '와항재', '써니마트/남창점',
       '대운산', '강양항', '울주도서관', '온양체육공원', 'FE01갤러리&카페', '서울산마트/울산언양점',
       '다이소/울산구영점', '배내고개', '파래소폭포', '구영공원', '다이소/울산굴화점', '박재상유적지',
       '다이소/울산남창점', '보라CC', '온산항제1부두', '은혜건축자재마트', '천상도서관', '신불평원',
       '태화강국가정원', '홈플러스/울산점', '십리대숲(은하수길)/태화강국가정원', '동천체육관', '울산시립미술관',
       '울산종합운동장', '공룡발자국공원', '롯데시네마/울산성남', '울산중앙시장', '태화종합시장',
       '하나로마트/태화점', '백양사', '함월루', '학성공원', '구역전시장', 'TTM스퀘어그랑테라스', '성남프라자',
       '삼성전자서비스/중울산센터', '함월구민운동장', '다이소/울산서동점', '뉴코아아울렛/울산성남점', '중구문화의전당',
       '신중앙시장', '울산종합운동장/보조경기장', '울산경상좌도병영성', '학성새벽시장', '메가박스/울산',
       '다이소/울산병영점', '학성동가구거리', '울산향교', '쿠쿠서비스센터/울산중구점', '태화루', '오성엑스포',
       '하나로마트/중울산농협', '울산배드민턴센터', '동천국민체육센터', '세계로마트/태화점', '외솔기념관',
       '신울산종합시장', 'GS더프레시/태화점', '울산중구도시관리공단수영장', '산전만화도서관', '쥬라리움/울산점',
       '유곡테니스장', '자연드림/울산남외점', '울산중구어린이역사과학체험관', '토이멀티샵/울산점',
       'CU/울산리버사이드호텔점', '코끼리공장', '우정시장', '다이소/울산성안점', '노브랜드/울산유곡점',
       '울산큰애기야시장', '다이소/울산태화루점', '다이소/태화동점', '레드락볼링장', '입화산참살이숲/제2오토캠핑장',
       '자연드림/울산유곡점', '그린피플', '함월유아숲체험원', '스마트/중구점', '롯데하이마트/복산점',
       '울산시립미술관/건축중(2022년01월06일개관예정)', '다이소/울산반구점', 'SH스포츠센터', '해남사',
       '다이소/울산학성점', '노브랜드/울산성남점', '약사동제방유적전시관', '동천야외물놀이장'], dtype=object)

In [122]:
len(up["url"].unique())

382

In [123]:
selected = ['장생포고래박물관', '울산대공원', '장생포고래문화마을', '태화강동굴피아',  '울산과학관', '고래생태체험관',  '울산항만선착장', '문수야구장', '정토사', '태화강전망대', '태화강국가정원', '대왕암공원', '일산해수욕장', '주전몽돌해변', '방어진활어센터', '주전항', '정자해수욕장', '강동몽돌해변', '태화강억새군락지', '진하해수욕장', '간절곶', '나사리해수욕장', '태화강생태관', '간월재', '솔개해수욕장', '울산옹기박물관', '백양사', '함월루', '학성공원', '태화루', '해남사', '약사동제방유적전시관', ]

In [124]:
len(selected)

32

In [125]:
up = up[up["url"].isin(selected)]

In [126]:
up.dropna(subset=["content"], inplace=True)

C:\Users\user\AppData\Local\Temp\ipykernel_12436\1655064918.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  up.dropna(subset=["content"], inplace=True)

In [127]:
## 각 url에 대해 몇 개의 리뷰가 있는지 확인
up["url"].value_counts()

url
태화강동굴피아       504
함월루           447
일산해수욕장        396
울산대공원         396
간절곶           394
진하해수욕장        392
강동몽돌해변        390
대왕암공원         386
장생포고래문화마을     384
태화강국가정원       384
백양사           372
고래생태체험관       370
장생포고래박물관      350
주전몽돌해변        350
태화루           330
나사리해수욕장       318
태화강생태관        288
학성공원          274
태화강전망대        258
솔개해수욕장        252
정자해수욕장        240
울산과학관         200
간월재           195
주전항           180
태화강억새군락지      158
약사동제방유적전시관    138
울산옹기박물관       137
방어진활어센터       127
해남사           127
정토사           106
울산항만선착장        84
문수야구장          83
Name: count, dtype: int64

In [128]:
# assertion:
assert len(up["url"].unique()) == len(selected)

In [129]:
up

,Unnamed: 0,url,content
1400,1400,장생포고래박물관,​울산 나들이 하는 날아이들과 어디로 가볼까 하다가울산으로 여행하게 된다면아이들 데...
1401,1401,장생포고래박물관,​​출발일.​첫째날 일정은 @울산장생포고래박물관.그 일대 고래어쩌고 관람장소들이 모...
1402,1402,장생포고래박물관,​우와아아아~~~!!!!!어머님댁 갔다가 그냥 쓱~ 댕겨오자 해서 아~~~~~무 준...
1403,1403,장생포고래박물관,울산 여행 볼거리 장생포 고래박물관 고래생태체험관 울산관광지 추천울오랜만에 울산 여...
1404,1404,장생포고래박물관,울산 장생포고래박물관 방문.​울산은 고래잡이로 유명했나보다.몰랐는데..항상 고래잡이...
...,...,...,...
85359,41343,약사동제방유적전시관,"국내 여행지 추천, 색다른 여행지국내 관광 명소 경남 울산 중구 여행당일치기 코스 ..."
85360,41344,약사동제방유적전시관,​​​​​​​​​​​​​​​​​​서늘해진 날씨에 자꾸만 떠나고만 싶은 가을여행.좋은...
85363,41347,약사동제방유적전시관,"(0, 0)"
85366,41350,약사동제방유적전시관,2019 올해의 관광도시로 선정된 울산중구감성충만 색다른 가을여행지 추천최근 태화강...
85372,41356,약사동제방유적전시관,인터넷에서 퍼온 글​<아름다운 건축물>​​원주: 뮤지엄 산​​용인: 백남준 아트센터...

In [130]:
import torch
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using device: {device}")

from transformers import AutoTokenizer, AutoModelForSequenceClassification, TextClassificationPipeline

# hugging face에서 토크나이저와 모델 불러오기
tokenizer = AutoTokenizer.from_pretrained("searle-j/kote_for_easygoing_people")
model = AutoModelForSequenceClassification.from_pretrained("searle-j/kote_for_easygoing_people")

# 감정 분석 모델 설정 
pipe = TextClassificationPipeline(
        model=model,
        tokenizer=tokenizer,
        device=0 if torch.cuda.is_available() else -1,
        return_all_scores=True,
        function_to_apply='sigmoid'
    )

Using device: cuda

Device set to use cuda:0
c:\Users\user\anaconda3\envs\travelnet\Lib\site-packages\transformers\pipelines\text_classification.py:106: UserWarning: `return_all_scores` is now deprecated,  if want a similar functionality use `top_k=None` instead of `return_all_scores=True` or `top_k=1` instead of `return_all_scores=False`.
  warnings.warn(

In [131]:
result = pipe(up["content"].iloc[0], max_length=512, truncation=True, padding="max_length")

positive_score = 0.0
negative_score = 0.0

for r in result[0]:
    if r["label"] in ["감동/감탄", "편안/쾌적", '신기함/관심', '즐거움/신남', '흐뭇함(귀여움/예쁨)', '행복', '기쁨', '안심/신뢰']:
        positive_score += r["score"]
    elif r["label"] in ["안타까움/실망",  '절망', '어이없음', '짜증', '역겨움/징그러움', '힘듦/지침', '부담/안_내킴', '재미없음', '불안/걱정', '불쾌함/싫음', '슬픔/우울', '화남/분노', '무서움/두려움', '우울함/허탈함', '피곤함/지침']:
        negative_score += r["score"]

pos_avg = positive_score / 8
neg_avg = negative_score / 15
print(pos_avg, neg_avg)
print(pos_avg - neg_avg)

0.7664254084229469 0.0027872365307606136
0.7636381718921863

In [132]:
from tqdm import tqdm

In [133]:
pos_score_list_all = []
neg_score_list_all = []
result_all_list = []

for i in tqdm((range(int(len(up) / 100) + 1))):
    result_all = pipe(up["content"].iloc[i*100:(i+1)*100].tolist(), truncation=True, max_length=512, padding="max_length")
    result_all_list.append(result_all)
    pos_score_list = []
    neg_score_list = []

    for j in range(len(result_all)):
        positive_score = 0.0
        negative_score = 0.0
        for r in result_all[j]:
            if r["label"] in ["감동/감탄", "편안/쾌적", '신기함/관심', '즐거움/신남', '흐뭇함(귀여움/예쁨)', '행복', '기쁨', '안심/신뢰']:
                positive_score += r["score"]
            elif r["label"] in ["안타까움/실망",  '절망', '어이없음', '짜증', '역겨움/징그러움', '힘듦/지침', '부담/안_내킴', '재미없음', '불안/걱정', '불쾌함/싫음', '슬픔/우울', '화남/분노', '무서움/두려움', '우울함/허탈함', '피곤함/지침']:
                negative_score += r["score"]
            
        pos_avg = positive_score / 8
        neg_avg = negative_score / 15
        pos_score_list.append(pos_avg)
        neg_score_list.append(neg_avg)
    
    pos_score_list_all += pos_score_list
    neg_score_list_all += neg_score_list

100%|██████████| 91/91 [02:41<00:00,  1.77s/it]

In [134]:
import pickle
with open("result_all_list.pkl", "wb") as f:
    pickle.dump(result_all_list, f)

In [135]:
len(pos_score_list_all), len(neg_score_list_all)

(9010, 9010)

In [136]:
up["pos_score"] = pos_score_list_all
up["neg_score"] = neg_score_list_all

C:\Users\user\AppData\Local\Temp\ipykernel_12436\746410708.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  up["pos_score"] = pos_score_list_all
C:\Users\user\AppData\Local\Temp\ipykernel_12436\746410708.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  up["neg_score"] = neg_score_list_all

In [137]:
up["total_score"] = up["pos_score"] - up["neg_score"]

C:\Users\user\AppData\Local\Temp\ipykernel_12436\1924383408.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  up["total_score"] = up["pos_score"] - up["neg_score"]

In [138]:
up

,Unnamed: 0,url,content,pos_score,neg_score,total_score
1400,1400,장생포고래박물관,​울산 나들이 하는 날아이들과 어디로 가볼까 하다가울산으로 여행하게 된다면아이들 데...,0.766425,0.002787,0.763638
1401,1401,장생포고래박물관,​​출발일.​첫째날 일정은 @울산장생포고래박물관.그 일대 고래어쩌고 관람장소들이 모...,0.593352,0.114517,0.478836
1402,1402,장생포고래박물관,​우와아아아~~~!!!!!어머님댁 갔다가 그냥 쓱~ 댕겨오자 해서 아~~~~~무 준...,0.065363,0.238194,-0.172830
1403,1403,장생포고래박물관,울산 여행 볼거리 장생포 고래박물관 고래생태체험관 울산관광지 추천울오랜만에 울산 여...,0.584822,0.008355,0.576467
1404,1404,장생포고래박물관,울산 장생포고래박물관 방문.​울산은 고래잡이로 유명했나보다.몰랐는데..항상 고래잡이...,0.123849,0.208544,-0.084695
...,...,...,...,...,...,...
85359,41343,약사동제방유적전시관,"국내 여행지 추천, 색다른 여행지국내 관광 명소 경남 울산 중구 여행당일치기 코스 ...",0.687245,0.003241,0.684004
85360,41344,약사동제방유적전시관,​​​​​​​​​​​​​​​​​​서늘해진 날씨에 자꾸만 떠나고만 싶은 가을여행.좋은...,0.730867,0.011007,0.719860
85363,41347,약사동제방유적전시관,"(0, 0)",0.127853,0.035460,0.092393
85366,41350,약사동제방유적전시관,2019 올해의 관광도시로 선정된 울산중구감성충만 색다른 가을여행지 추천최근 태화강...,0.718536,0.003077,0.715459
85372,41356,약사동제방유적전시관,인터넷에서 퍼온 글​<아름다운 건축물>​​원주: 뮤지엄 산​​용인: 백남준 아트센터...,0.079812,0.008613,0.071198

In [139]:
up[["url", "pos_score", "neg_score", "total_score"]].to_json("ulsan_place_score_0513.json", orient="records", force_ascii=False, lines=True)
up[["url", "pos_score", "neg_score", "total_score"]].to_csv("ulsan_place_score_0513.csv", index=False, encoding="utf-8-sig")

In [140]:
## unique한 url에 대해 score 기준으로 평균값 계산
up_avg = up.groupby("url").agg({"pos_score": "mean", "neg_score": "mean", "total_score": "mean"}).reset_index()

In [141]:
## 각 url의 record 수 확인
up_avg["count"] = up.groupby("url").size().values

In [142]:
up_avg = up_avg.sort_values("total_score", ascending=False)

In [143]:
up_avg

           url  pos_score  neg_score  total_score  count
26    태화강억새군락지   0.710754   0.020357     0.690396    158
1          간절곶   0.704909   0.023329     0.681580    394
16   장생포고래문화마을   0.682296   0.024522     0.657774    384
15      일산해수욕장   0.680651   0.026621     0.654030    396
4      나사리해수욕장   0.682944   0.032277     0.650667    318
2       강동몽돌해변   0.680457   0.031992     0.648466    390
30         함월루   0.672265   0.024427     0.647837    447
23     태화강국가정원   0.669190   0.021663     0.647528    384
5        대왕암공원   0.671715   0.025469     0.646246    386
9       솔개해수욕장   0.675390   0.029675     0.645715    252
12       울산대공원   0.667146   0.023197     0.643949    396
22      진하해수욕장   0.668880   0.027843     0.641037    392
25      태화강생태관   0.660478   0.020003     0.640475    288
3      고래생태체험관   0.669333   0.029778     0.639555    370
18      정자해수욕장   0.666824   0.038686     0.628138    240
11       울산과학관   0.645630   0.021452     0.624178    200
20      주전몽돌해변   0.649920   0.035527     0.614393    350
24     태화강동굴피아   0.640182   0.031074     0.609108    504
17    장생포고래박물관   0.628137   0.027427     0.600710    350
28         태화루   0.628541   0.028595     0.599946    330
13     울산옹기박물관   0.611070   0.013712     0.597358    137
8          백양사   0.620846   0.023894     0.596951    372
0          간월재   0.637548   0.042611     0.594938    195
7      방어진활어센터   0.609978   0.030040     0.579938    127
27      태화강전망대   0.584816   0.027841     0.556975    258
29        학성공원   0.557442   0.027194     0.530248    274
6        문수야구장   0.556010   0.038037     0.517973     83
19         정토사   0.524105   0.030689     0.493416    106
21         주전항   0.518204   0.042812     0.475393    180
10  약사동제방유적전시관   0.427669   0.035404     0.392266    138
31         해남사   0.385042   0.031840     0.353203    127
14     울산항만선착장   0.374388   0.041561     0.332827     84

In [150]:
## total_score와 count를 정규분포로 변환하고, Z-score를 계산
up_avg["total_score_z"] = (up_avg["total_score"] - up_avg["total_score"].mean()) / up_avg["total_score"].std()
up_avg["count_z"] = (up_avg["count"] - up_avg["count"].mean()) / up_avg["count"].std()

# Z-Score 합산 후 해당 값 기준으로 정렬
up_avg["z_score"] = up_avg["total_score_z"] * 0.9 + up_avg["count_z"] * 0.1
up_avg = up_avg.sort_values("z_score", ascending=False)

In [151]:
up_avg

,url,pos_score,neg_score,total_score,count,total_score_z,count_z,z_score
1,간절곶,0.704909,0.023329,0.681580,394,1.025313,0.941499,1.016932
26,태화강억새군락지,0.710754,0.020357,0.690396,158,1.122464,-1.034655,0.906752
16,장생포고래문화마을,0.682296,0.024522,0.657774,384,0.762968,0.857764,0.772448
15,일산해수욕장,0.680651,0.026621,0.654030,396,0.721707,0.958246,0.745361
30,함월루,0.672265,0.024427,0.647837,447,0.653470,1.385297,0.726653
2,강동몽돌해변,0.680457,0.031992,0.648466,390,0.660392,0.908005,0.685154
23,태화강국가정원,0.669190,0.021663,0.647528,384,0.650055,0.857764,0.670826
5,대왕암공원,0.671715,0.025469,0.646246,386,0.635930,0.874511,0.659788
4,나사리해수욕장,0.682944,0.032277,0.650667,318,0.684654,0.305111,0.646700
12,울산대공원,0.667146,0.023197,0.643949,396,0.610619,0.958246,0.645382
22,진하해수욕장,0.668880,0.027843,0.641037,392,0.578528,0.924752,0.613151
3,고래생태체험관,0.669333,0.029778,0.639555,370,0.562201,0.740535,0.580034
9,솔개해수욕장,0.675390,0.029675,0.645715,252,0.630081,-0.247543,0.542319
25,태화강생태관,0.660478,0.020003,0.640475,288,0.572340,0.053905,0.520497
24,태화강동굴피아,0.640182,0.031074,0.609108,504,0.226683,1.862588,0.390274
18,정자해수욕장,0.666824,0.038686,0.628138,240,0.436389,-0.348025,0.357948
20,주전몽돌해변,0.649920,0.035527,0.614393,350,0.284915,0.573064,0.313730
11,울산과학관,0.645630,0.021452,0.624178,200,0.392750,-0.682966,0.285179
17,장생포고래박물관,0.628137,0.027427,0.600710,350,0.134133,0.573064,0.178026
8,백양사,0.620846,0.023894,0.596951,372,0.092713,0.757282,0.159170
28,태화루,0.628541,0.028595,0.599946,330,0.125719,0.405593,0.153706
0,간월재,0.637548,0.042611,0.594938,195,0.070523,-0.724834,-0.009013
13,울산옹기박물관,0.611070,0.013712,0.597358,137,0.097195,-1.210499,-0.033574
7,방어진활어센터,0.609978,0.030040,0.579938,127,-0.094768,-1.294235,-0.214715
27,태화강전망대,0.584816,0.027841,0.556975,258,-0.347819,-0.197301,-0.332767
29,학성공원,0.557442,0.027194,0.530248,274,-0.642350,-0.063325,-0.584447
6,문수야구장,0.556010,0.038037,0.517973,83,-0.777612,-1.662670,-0.866118
19,정토사,0.524105,0.030689,0.493416,106,-1.048228,-1.470079,-1.090413
21,주전항,0.518204,0.042812,0.475393,180,-1.246840,-0.850437,-1.207200
10,약사동제방유적전시관,0.427669,0.035404,0.392266,138,-2.162886,-1.202126,-2.066810
31,해남사,0.385042,0.031840,0.353203,127,-2.593354,-1.294235,-2.463442
14,울산항만선착장,0.374388,0.041561,0.332827,84,-2.817887,-1.654297,-2.701528

In [152]:
up_avg.to_json("ulsan_place_score_avg_0513.json", orient="records", force_ascii=False, lines=True)
up_avg.to_csv("ulsan_place_score_avg_0513.csv", index=False, encoding="utf-8-sig")